### ISSUE TITLE
Doesn't show the status badge on bitbucket

### ISSUE THREAD

**Issue by coorasse** [gion/BitShip#16]
It worked for a couple of weeks and now it does not anymore. 

It does not show the badge in any project.

I know these information are not enough but I have no idea on how to debug and send more informations. 

Just ask and I'll help fixing the issue.

I double-checked the api-key and is correct

**Comment by ivokund** [comment]
Just installed the extension and I seem to be having the same issue.

**Comment by gion** [comment]
Hy guys, thanks for opening this issue. I am aware that something went wrong, and I intend to fix it asap.

**Comment by gion** [comment]
This issue was due to the fact that bitbucket updated their single pull-request page url pattern from the singular **pull-request** to the plural **pull-requests**. This affected the extension in the way that it didn't execute any script on the pull request page because it wasn't matching the url pattern that was previously defined.

I am currently in vacation so this is why I responded with this delay, but I'm glad I could figure it out in such a short time.

These kind of issues may still appear in the future because the extension is relying on scraping data from bitbucket, so I am thankful and encourage you guys to let me know whenever such issues occur.

The [new release](https://github.com/gion/BitShip/releases/tag/v0.1.6) contains this fix and the [official chrome extension page](https://chrome.google.com/webstore/detail/bitship/heagnhmcighohcbdgndgmebmcpfgadbd?hl=en) should get updated any minute now.

Thanks for your input, guys!

**Comment by ivokund** [comment]
Thanks for the update! However, I'm on version 0.1.6 and still not seeing anything on my pull request page. Any way I can debug, what's going on?

The URL I'm testing with is `https://bitbucket.org/opus-online/adsales/pull-requests/702/as-920-tellimuse-suhtluse-countide/diff`

---

Nevermind, it seems to work fine now. Thanks!

**Comment by gion** [comment]
@ivokund I see. I might have missed the case where the pull request url has more parameters than id and name (such as **diff**).  
Thanks for pointing this issue out. I will do my best to resolve it ASAP.

**Comment by gion** [comment]
Opened another issue for @ivokund's raised problem.
Closing this issue.
